name: retail_demand
version: "1.0.0"
config-version: 2

profile: retail_demand

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retail_demand:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
